version: "3"
services:
    redis:
        image: redis

    db:
        image: postgres:15-alpine
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
        
    vote:
        image: voting-app
        ports:
            - 5000:80
        depends_on:
            - redis
            
    worker:
        image: worker-app
        depends_on:
            - redis
            - db
        
    result:
        image: result-app
        ports:
            - 5001:80
        depends_on:
            - db